language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install pycurl"
before_script:
  - mkdir $HOME/.pyload
  - cp tests/test_conf/* $HOME/.pyload/
# command to run tests
script:
  - bash tests/test.sh
